name: Davy Jones Seafoods
favicon: null
layout_spectrum: 0.42273339652456343
typography_spectrum: 0.7951337250415236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.34999857004731894
  lightness: 0.6044068702030927
  saturation: 0.3103867475874722
  rhythmicContrast: 0.724509795429185
purpose: []
