name: Davy Jones Seafoods
favicon: null
layout_spectrum: 0.0030071530491113663
typography_spectrum: 0.9412056726869196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4137001365888864
  lightness: 0.7347148237749934
  saturation: 0.4838457456789911
  rhythmicContrast: 0.4303982623387128
purpose: []
