name: Davy Jones Seafoods
favicon: null
layout_spectrum: 0.5050787720829248
typography_spectrum: 0.4170213
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6DA7C5'
    - '#42748A'
    - '#503631'
    - '#BF987B'
    - '#B7BED1'
  brandStrength: 0.5340425
  lightness: 0.518258752534166
  saturation: 0.134993483312428
  rhythmicContrast: 0.6203086618334055
purpose: []
