title: DavyJonesSeafoods.com
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.5050787720829248
favicon: null
name: Davy Jones Seafoods
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5340425
  lightness: 0.7744681
  saturation: 0.3106383
  rhythmicContrast: 0.6203086
  brandColors:
    - '#6DA7C5'
    - '#42748A'
    - '#503631'
    - '#BF987B'
    - '#B7BED1'
typography_spectrum: 0.4170213
