name: Davy Jones Seafoods
favicon: null
layout_spectrum: 0.47031466756016016
typography_spectrum: 0.9407417054753751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1792843067087233
  lightness: 0.1637480470817536
  saturation: 0.10875967447645962
  rhythmicContrast: 0.2232560182455927
purpose: []
