name: Davy Jones Seafoods
favicon: null
layout_spectrum: 0.633967240806669
typography_spectrum: 0.4589984880294651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.19824882736429572
  lightness: 0.6074766160454601
  saturation: 0.3116740635596216
  rhythmicContrast: 0.14656381984241307
purpose: []
