name: Davy Jones Seafoods
favicon: null
layout_spectrum: 0.7247519022785127
typography_spectrum: 0.45837922603823245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07060325960628688
  lightness: 0.24578366242349148
  saturation: 0.035487849498167634
  rhythmicContrast: 0.33399618533439934
purpose: []
