title: DavyJonesSeafoods.com
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: Davy Jones Seafoods
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5340425
  saturation: 0.3106383
  brandColors:
    - '#5F758B'
    - '#9CACBD'
    - '#FFFFFF'
    - '#644146'
    - '#C84C3A'
  lightness: 0.7744681
  rhythmicContrast: 0.6203086
typography_spectrum: 0.4170213
