name: Davy Jones Seafoods
favicon: null
layout_spectrum: 0.822028435068205
typography_spectrum: 0.8097165699582547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.01693547028116882
  lightness: 0.44142502592876554
  saturation: 0.09995766473002732
  rhythmicContrast: 0.41932100942358375
purpose: []
