name: Davy Jones Seafoods
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4170213
title: DavyJonesSeafoods.com
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5F758B'
    - '#9CACBD'
    - '#FFFFFF'
    - '#644146'
    - '#C84C3A'
  brandStrength: 0.5340425
  lightness: 0.7744681
  saturation: 0.3106383
  rhythmicContrast: 0.6203086
purpose: []
